# Trained from: models/sota/model_3d/recgan_3d

DATASET_INPUT_FOLDER: "parse2022"
DATASET_OUTPUT_FOLDER: "parse2022_LC_64_50_recgan_3d"
DATA_CROP_STRIDE: 64
DATA_CROP_SIZE: 64
DENSITY_LOWER_THRESHOLD: 0.0001  # 0.00001
DENSITY_UPPER_THRESHOLD: 0.9
TASK_TYPE: "LOCAL_CONNECTIVITY"
START_INDEX: 1
STOP_INDEX: 50
INCLUDE_2D_PROJECTIONS: False  # Works directly with 3D data, so no need to include 2D projections


# Predict Pipeline:
APPLY_FUSION: False

#APPLY_INPUT_MERGE_2D: False
#APPLY_THRESHOLD_2D: True
#THRESHOLD_2D: 0.2
#APPLY_NOISE_FILTER_2D: False
#HARD_NOISE_FILTER_2D: True
#PREDICT_CONNECTIVITY_TYPE_2D: 4

APPLY_INPUT_MERGE_3D: False
APPLY_THRESHOLD_3D: True
THRESHOLD_3D: 0.5
APPLY_NOISE_FILTER_3D: False
HARD_NOISE_FILTER_3D: False
PREDICT_CONNECTIVITY_TYPE_3D: 6

MERGE_WITH_SOURCE: False