# Trained from: https://github.com/OfirGiladBGU/convolutional_occupancy_networks

DATASET_INPUT_FOLDER: "pares2022_conv_onet"
DATASET_OUTPUT_FOLDER: "parse2022_LC_full_50_conv_onet"
DATA_CROP_STRIDE: -1
DATA_CROP_SIZE: -1
DENSITY_LOWER_THRESHOLD: -0.1
DENSITY_UPPER_THRESHOLD: 1.1
TASK_TYPE: "LOCAL_CONNECTIVITY"
START_INDEX: 1
STOP_INDEX: 50
INCLUDE_2D_PROJECTIONS: False  # Works directly with 3D data, so no need to include 2D projections


# Predict Pipeline:
APPLY_FUSION: False
MERGE_WITH_SOURCE: False

#APPLY_INPUT_MERGE_2D: False
#APPLY_THRESHOLD_2D: True
#THRESHOLD_2D: 0.2
#APPLY_NOISE_FILTER_2D: False
#HARD_NOISE_FILTER_2D: True
#PREDICT_CONNECTIVITY_TYPE_2D: 4

APPLY_INPUT_MERGE_3D: True
APPLY_THRESHOLD_3D: True
THRESHOLD_3D: 0.5
APPLY_NOISE_FILTER_3D: False
HARD_NOISE_FILTER_3D: False
PREDICT_CONNECTIVITY_TYPE_3D: 6