DATASET_INPUT_FOLDER: "PipeForge3DMesh"
DATASET_OUTPUT_FOLDER: "PipeForge3DMesh_SC_32"
DATA_CROP_STRIDE: 16
DATA_CROP_SIZE: 32
DENSITY_LOWER_THRESHOLD: 0.1
DENSITY_UPPER_THRESHOLD: 0.9
TASK_TYPE: "SINGLE_COMPONENT"
START_INDEX: -1
STOP_INDEX: -1

# Meshes from PipeForge3D (in Tree Mode)
